language: php
dist: bionic
sudo: false

php:
  - 7.2
  - 7.3

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --stable
  - composer --version

install:
  - composer --verbose --no-check-all --no-check-publish validate
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-suggest --profile
  - composer run-script install-bootstrap-sass

script:
  - cd $TRAVIS_BUILD_DIR/web
  - $TRAVIS_BUILD_DIR/vendor/bin/drush -y si config_installer config_installer_sync_configure_form.sync_directory="../config/sync" --db-url=$SIMPLETEST_DB
  - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do sleep 2s; done > /dev/null
  - $TRAVIS_BUILD_DIR/vendor/bin/drush status --field=bootstrap
  - $TRAVIS_BUILD_DIR/vendor/bin/drupal site:status
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
  # Ignore Setup group temporarily, @see https://www.drupal.org/node/2962157
  #- $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  #  -c core --verbose
  #  --exclude-group Composer,DependencyInjection,PageCache,Setup
  #  --coverage-text --colors=never
  #  --testsuite unit
